namespace MvcApplication.Models.Entities.PlayerDetails
{
  public class Achievements
  {
    public long MasterGunner { get; set; }
    public long Hunter { get; set; }
    public long Bombardier { get; set; }
    public long Defender { get; set; }
    public long Survivor { get; set; }
    public long PatrolDuty { get; set; }
    public long Reaper { get; set; }
    public long NaydinSMedal { get; set; }
    public long Invader { get; set; }
    public long Invincible { get; set; }
    public long CoolHeaded { get; set; }
    public long Kamikaze { get; set; }
    public long Lucky { get; set; }
    public long Lumberjack { get; set; }
    public long HighCaliber { get; set; }
    public long LongestSeriesOfSurvivor { get; set; }
    public long LongestSeriesOfInvincible { get; set; }
    public long LongestSeriesOfReaper { get; set; }
    public long LongestSeriesOfMasterGunner { get; set; }
    public long LongestSeriesOfSharpshooter { get; set; }
    public long SeniorTechnicalEngineer { get; set; }
    public long TechnicalEngineerChina { get; set; }
    public long TechnicalEngineerFrance { get; set; }
    public long TechnicalEngineerGermany { get; set; }
    public long TechnicalEngineerJapan { get; set; }
    public long TechnicalEngineerUK { get; set; }
    public long TechnicalEngineerUSA { get; set; }
    public long TechnicalEngineerUSSR { get; set; }
    public long AbramsMedal { get; set; }
    public long BillottesMedal { get; set; }
    public long BoeltersMedal { get; set; }
    public long BrothersInArms { get; set; }
    public long BrunosMedal { get; set; }
    public long BurdasMedal { get; set; }
    public long CariusMedal { get; set; }
    public long CrucialContribution { get; set; }
    public long DeLangladesMedal { get; set; }
    public long DumitrusMedal { get; set; }
    public long EkinsMedal { get; set; }
    public long FadinsMedal { get; set; }
    public long HalonensMedal { get; set; }
    public long RaseiniaiHeroesMedal { get; set; }
    public long KaysMedal { get; set; }
    public long KnispelsMedal { get; set; }
    public long KolobanovsMedal { get; set; }
    public long PoolsMedal { get; set; }
    public long LavrinenkosMedal { get; set; }
    public long LeclercsMedal { get; set; }
    public long LehvaslaihosMedal { get; set; }
    public long NicolssMedal { get; set; }
    public long OrliksMedal { get; set; }
    public long OskinsMedal { get; set; }
    public long PascuccisMedal { get; set; }
    public long PopelsMedal { get; set; }
    public long RadleyWalterssMedal { get; set; }
    public long TamadaYoshiosMedal { get; set; }
    public long TarczaysMedal { get; set; }
    public long MouseTrap { get; set; }
    public long ValleyOfPattons { get; set; }
    public long Raider { get; set; }
    public long Scout { get; set; }
    public long TheLionOfSinai { get; set; }
    public long Sniper { get; set; }
    public long TankSniper { get; set; }
    public long SteelWall { get; set; }
    public long Spartan { get; set; }
    public long Support { get; set; }
    public long MasterTanker { get; set; }
    public long ExpertChina { get; set; }
    public long ExpertFrance { get; set; }
    public long ExpertGermany { get; set; }
    public long ExpertJapan { get; set; }
    public long ExpertUK { get; set; }
    public long ExpertUSA { get; set; }
    public long ExpertUSSR { get; set; }
    public long Sharpshooter { get; set; }
    public long TopGun { get; set; }
  }
}
