namespace WargamingApiService.Enums
{
  public enum RequestTarget
  {
    AccountList,
    AccountInfo,
    AccountRatings,
    AccountTanks,
    AccountAchievements,
    AuthLogin,
    AuthProlongate,
    AuthLogout,
    ClanList,
    ClanInfo,
    ClanBattles,
    ClanTop,
    ClanProvinces,
    ClanVictorypoints,
    ClanMembersinfo,
    EncyclopediaTanks,
    EncyclopediaTankinfo,
    EncyclopediaTankengines,
    EncyclopediaTankturrets,
    EncyclopediaTankradios,
    EncyclopediaTankchassis,
    EncyclopediaTankguns,
    EncyclopediaAchievements,
    TanksStats,
    TanksAchievements
  }
}
