namespace WargamingTypesLibrary.Enums
{
  public enum RequestTarget
  {
    AccountList,
    AccountInfo,
    AccountRatings,
    AccountTanks,
    AccountAchievements,
    AuthLogin,
    AuthProlongate,
    AuthLogout,
    ClanList,
    ClanInfo,
    ClanBattles,
    ClanTop,
    ClanProvinces,
    ClanVictorypoints,
    ClanMembersinfo,
    EncyclopediaTanks,
    EncyclopediaTankInfo,
    EncyclopediaTankEngines,
    EncyclopediaTankTurrets,
    EncyclopediaTankRadios,
    EncyclopediaTankChassis,
    EncyclopediaTankGuns,
    EncyclopediaAchievements,
    TanksStats,
    TanksAchievements
  }
}
